// Restaurant 
export const SEARCH_BY_SUBURB = 'SEARCH_BY_SUBURB';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const SEARCH_BY_CITY = 'SEARCH_BY_CITY';
export const SEARCH_BY_CUISINE = 'SEARCH_BY_CUISINE';
export const CLEAR_SEARCHED_RESTAURANTS = 'CLEAR_SEARCHED_RESTAURANTS';
export const SEARCH_RESTAURANTS_NEARBY = 'SEARCH_RESTAURANTS_NEARBY';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';

// User
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';